### ISSUE TITLE
Timezone adjustment option

### ISSUE THREAD

**Issue by buzzkc** [heskja/MMM-CalendarWeek#34]
I noticed when adding a sunrise/sunset calendar to the list of calendars that the timezone was off. Is there a configuration to adjust this or can it be updated to use the system timezone setting to adjust for timezone differences?

This is the calendar I was loading...
https://calendar.google.com/calendar/ical/i_12.201.176.150%23sunrise%40group.v.calendar.google.com/public/basic.ics

**Comment by heskja** [comment]
Hi,
I think this is an issue with the kind of calendar you are trying to fetch to be honest. I created a new event in my Google Calendar and set a different timezone for that event (UTC instead of GMT+2). Shows up correctly in my MagicMirror, meaning at the GMT+2 equivalent start time. 

Problem is, as far as I can tell, that the calendar you are trying to fetch actually gives you an all-day event with a string representation of sunrise and sunset. I cannot modify that. Will close the issue.
